import type {Metadata, Viewport} from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "resume",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: 1024
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
    <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-full`}
        style={{ background: "#202020" }}
      >
          {children}
      </body>
    </html>
  );
}
